[project]
name = "uc-intg-lyngdorf"
version = "0.6.6"
description = "Unfolded Circle Lyngdorf Integration"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.9.0",
    "certifi>=2024.8.30",
    "pillow>=11.3",
    "pyee>=9.0.0",
    "ucapi==0.5.2",
    "ucapi-framework==1.8.4",
    "zeroconf>=0.147.0",
]

[dependency-groups]
dev = [
    "ruff>=0.8.0",
]