#!/usr/bin/env bash
set -e

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd ${ROOT}

# Use system python3 to create venv if missing
PYTHON="$(which python3)"

if [ ! -d ".venv" ]; then
    echo "Creating virtual environment..."
    ${PYTHON} -m venv ./.venv
else
    echo "Using existing virtual environment."
fi

# Use venv python explicitly
PYTHON_VENV="$ROOT/.venv/bin/python"
PIP="$PYTHON_VENV -m pip"

# Upgrade pip and install dependencies
${PIP} install --upgrade pip
${PIP} install --requirement requirements.txt

# Configure git hooks
git config --local core.hooksPath git-hooks